export const AUTH_LOGIN_REQUEST = 'auth/login/request';
export const AUTH_LOGIN_SUCCESS = 'auth/login/success';
export const AUTH_LOGIN_FAILURE = 'auth/login/failure';

export const AUTH_LOGOUT = 'auth/logout';


export const SET_TAGS_REQUEST = 'SET_TAGS_REQUEST'
export const SET_TAGS_FAILURE = 'SET_TAGS_FAILURE'
export const SET_TAGS_SUCCESS = 'SET_TAGS_SUCCESS'



export const SET_ADVERTS_REQUEST = 'SET_ADVERTS_REQUEST'
export const SET_ADVERTS_SUCCESS = 'SET_ADVERTS_SUCCESS'
export const SET_ADVERTS_FAILURE = 'SET_ADVERTS_FAILURE'




export const SET_SELECTED_ADVERTS_REQUEST = 'SET_SELECTED_ADVERT_REQUEST'
export const SET_SELECTED_ADVERTS_SUCCESS = 'SET_SELECTED_ADVERTS_SUCCESS'
export const SET_SELECTED_ADVERTS_FAILURE = 'SET_SELECTED_ADVERTS_FAILURET'




export const SET_CREATE_ADVERTS_SUCCESS = 'SET_CREATE_ADVERTS_SUCCESS'
export const SET_CREATE_ADVERTS_REQUEST = 'SET_CREATE_ADVERTS_REQUEST'
export const SET_CREATE_ADVERTS_FAILURE = 'SET_CREATE_ADVERT_FAILURE'



export const SET_DELETE_ADVERTS_REQUEST = 'SET_DELETE_ADVERT_REQUEST '
export const SET_DELETE_ADVERTS_SUCCESS = 'SET_DELETE_ADVERTS_SUCCESS'
export const SET_DELETE_ADVERTS_FAILURE = 'SET_DELETE_ADVERTS_FAILUR'










